repo = "rustc_codegen_gcc"
filter = ":~(history=\"keep-trivial-merges,no-splice\")[:rev(<=8c858fb5fbb077eaa776302b9601cf084f12aa46:prefix=compiler/rustc_codegen_gcc,<=7d2cd0fbc092625ea371da704f15f80216d2220e:SQUASH)]:/compiler/rustc_codegen_gcc"
filter-version = 2
pull-mode = "Latest"
